Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end

GraniteCave_F1_Item_Aggronite::
	finditem ITEM_AGGRONITE 
	end

Route120_Absolite::
	finditem ITEM_ABSOLITE
	end

GraniteCave_F2_Item_Steelixite::
	finditem ITEM_STEELIXITE
	end

ShoalCave_Ice_Room_Abomasite::
	finditem ITEM_ABOMASITE
	end

MirageTower_F4_Aerodactylite::
	finditem ITEM_AERODACTYLITE
	end

SlateportCity_Alakazite::
	finditem ITEM_ALAKAZITE
	end

New_Mauville_Ampharosite::
	finditem ITEM_AMPHAROSITE
	end

Mt_Pyre_Summit_Banettite::
	finditem ITEM_BANETTITE
	end

Dewford_Meadows_Beedrillite::
	finditem ITEM_BEEDRILLITE
	end

MagmaHideout_Cameruptite::
	finditem ITEM_CAMERUPTITE
	end

JaggedPass_Chariztardite_X::
	finditem ITEM_CHARIZARDITE_X
	end

DesertPass_Garchompite::
	finditem ITEM_GARCHOMPITE
	end

Verdantturf_Gardevoirite::
	finditem ITEM_GARDEVOIRITE
	end

Mt_Pyre_Exterior_Gengarite::
	finditem ITEM_GENGARITE
	end

Shoal_Cave_High_Tide_Glalitite::
	finditem ITEM_GLALITITE
	end

Route115_Heracronite::
	finditem ITEM_HERACRONITE
	end

Fiery_Path_Houndoominite::
	finditem ITEM_HOUNDOOMINITE
	end

Safari_Zone_North_West_Kangaskhanite::
	finditem ITEM_KANGASKHANITE
	end

Southern_Island_Latiasite::
	finditem ITEM_LATIASITE
	end

Southern_Island_Latiosite::
	finditem ITEM_LATIOSITE
	end
	
Abandoned_Ship_Lopunnite::
	finditem ITEM_LOPUNNITE
	end

Abandoned_Ship_Dive_Lucarionite::
	finditem ITEM_LUCARIONITE
	end

Route110_Manectite::
	finditem ITEM_MANECTITE
	end

Route117_Mawilite::
	finditem ITEM_MAWILITE
	end

Rusturf_Tunnel_F1_Medichamite::
	finditem ITEM_MEDICHAMITE
	end

Floral_Cave_Scizorite::
	finditem ITEM_SCIZORITE
	end

Gathering_Cave_Slowbronite::
	finditem ITEM_SLOWBRONITE
	end

HiddenRoot_Grotto_Pinsirite::
	finditem ITEM_PINSIRITE
	end

Victory_Road_Metagrossite::
	finditem ITEM_METAGROSSITE

Route120_Pidgeotite::
	finditem ITEM_PIDGEOTITE
	end

Rusturf_Tunnel_Sablenite::
	finditem ITEM_SABLENITE
	end

Meteor_Falls_Salamencite::
	finditem ITEM_SALAMENCITE
	end

Scorched_Slab_Tyranitarite::
	finditem ITEM_TYRANITARITE
	end

Aqua_Hideout_Sharpedonite::
	finditem ITEM_SHARPEDONITE
	end

Rusturf_Tunnel_F1_Rare_Candy::
	finditem ITEM_RARE_CANDY
	end

Rusturf_Tunnel_F1_Hyper_Potion::
	finditem ITEM_HYPER_POTION
	end

Rusturf_Tunnel_F1_Heat_Rock::
	finditem ITEM_HEAT_ROCK
	end

TrickHouse_Room_Assualt_Vest::
	finditem ITEM_ASSAULT_VEST
	end

Route110_TrickHousePuzzle_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end

TrickHouse_Room_Dusk_Stone::
	finditem ITEM_DUSK_STONE
	end

TrickHouse_Room_Choice_Band::
	finditem ITEM_CHOICE_BAND
	end

TrickHouse_Room_Choice_Scarf::
	finditem ITEM_CHOICE_SCARF
	end

TrickHouse_Room_Choice_Specs::
	finditem ITEM_CHOICE_SPECS
	end

TrickHouse_Room_Destiny_Knot::
	finditem ITEM_DESTINY_KNOT
	end

UnderwaterRoute124_Relicanthite::
	finditem ITEM_RELICANTHITE
	end
